# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Exploring Colorado Wine Country in Paonia, Grand Junction and Aspen :: Colorado Wine Classes, Events"
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  The mission of Savor Each Glass is to promote wine and food in Colorado - including Palisade,
  Paonia and the North Fork valley - through teaching wine classes, pairing the regions fine
  wines with local cuisine, and helping Colorado's burgeoning wine makers get the word out
  on some of the great wines they are producing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SavorEachGlass

# Custom collections
collections:
  articles:
    output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ['Gemfile', 'Gemfile.lock', 'README.md',
'savoreachglass.code-workspace', '.ruby-gemset', '.ruby-version']
